// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhAXFV16WU9Ggv5gTY3Anc_yqmkuIpX7Q',
    appId: '1:854104840843:web:96aa82eea68a9ecd87528e',
    messagingSenderId: '854104840843',
    projectId: 'tv-series-188ee',
    authDomain: 'tv-series-188ee.firebaseapp.com',
    storageBucket: 'tv-series-188ee.appspot.com',
    measurementId: 'G-LTGV3WWG2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiV-jbUz1pmHxLuFe70euFGtzlNOc6yCM',
    appId: '1:854104840843:android:9f9f0279be99f6aa87528e',
    messagingSenderId: '854104840843',
    projectId: 'tv-series-188ee',
    storageBucket: 'tv-series-188ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4dfanNejcVd6R9MVV0OV9pBr-tv3Wvk8',
    appId: '1:854104840843:ios:e20bcf2552d1066a87528e',
    messagingSenderId: '854104840843',
    projectId: 'tv-series-188ee',
    storageBucket: 'tv-series-188ee.appspot.com',
    iosClientId: '854104840843-lug50f8a8q7p53nbatktgfot4qmbfq63.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
